[package]
name = "kronos"
version = "0.1.0"
edition = "2024"

[dependencies]
blake3 = "1.8.2"
postcard = { version = "1.1.3", features = ["alloc"] }
rs_merkle = "1.4"
serde = { version = "1.0", features = ["derive"] }
